export const robotActionTypes = {
  REQUEST_ROBOT_PENDING: 'REQUEST_ROBOT_PENDING',
  REQUEST_ROBOT_SUCCESS: 'REQUEST_ROBOT_SUCCESS',
  REQUEST_ROBOT_FAILED: 'REQUEST_ROBOT_FAILED',
  CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD'
}